# Generated by Django 6.0.2 on 2026-03-19 23:23

import apps.core.mixins
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_alter_secuenciadocumento_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONTABILIZADO', 'Contabilizado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('INTEGRACION', 'Integracion')], default='MANUAL', max_length=20)),
                ('glosa', models.CharField(max_length=255)),
                ('referencia_tipo', models.CharField(blank=True, max_length=80)),
                ('referencia_id', models.UUIDField(blank=True, null=True)),
                ('total_debe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_haber', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cuadrado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PlanCuenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=20)),
                ('acepta_movimientos', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='contabilidad.plancuenta')),
            ],
            options={
                'ordering': ['codigo'],
            },
            bases=(apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('glosa', models.CharField(blank=True, max_length=255)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.asientocontable')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.plancuenta')),
            ],
            options={
                'ordering': ['creado_en', 'id'],
            },
            bases=(apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['empresa', 'estado', 'fecha'], name='contabilida_empresa_0c3f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['empresa', 'origen', 'fecha'], name='contabilida_empresa_2ac4de_idx'),
        ),
        migrations.AddConstraint(
            model_name='asientocontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uniq_asiento_contable_empresa_numero'),
        ),
        migrations.AddIndex(
            model_name='plancuenta',
            index=models.Index(fields=['empresa', 'tipo', 'activa'], name='contabilida_empresa_3f0a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='plancuenta',
            index=models.Index(fields=['empresa', 'codigo'], name='contabilida_empresa_884f63_idx'),
        ),
        migrations.AddConstraint(
            model_name='plancuenta',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_plan_cuenta_empresa_codigo'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['empresa', 'asiento'], name='contabilida_empresa_a0aad8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['empresa', 'cuenta'], name='contabilida_empresa_cf9b51_idx'),
        ),
    ]
