# Generated by Django 6.0.2 on 2026-03-20 00:28

import apps.core.mixins
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('core', '0019_alter_movimientobancario_estado_contable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCuentaContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(choices=[('CAJA', 'Caja'), ('BANCO', 'Banco'), ('CLIENTES', 'Clientes'), ('IVA_CREDITO', 'IVA credito fiscal'), ('PROVEEDORES', 'Proveedores'), ('IVA_DEBITO', 'IVA debito fiscal'), ('CAPITAL', 'Capital'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras y servicios')], max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_funcionales', to='contabilidad.plancuenta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            options={
                'ordering': ['clave'],
                'indexes': [models.Index(fields=['empresa', 'clave', 'activa'], name='contabilida_empresa_8cbe66_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'clave'), name='uniq_configuracion_cuenta_contable_empresa_clave')],
            },
            bases=(apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
