# Generated by Django 6.0.2 on 2026-03-19 20:09

import apps.core.mixins
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0003_alter_direccion_tipo'),
        ('core', '0015_cuentaporcobrar_cuentaporpagar_tipocambio'),
        ('inventario', '0005_stocklote_stockserie_and_more'),
        ('productos', '0006_producto_usa_series_listaprecio_listaprecioitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaDespacho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('numero', models.CharField(max_length=50)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('fecha_despacho', models.DateField()),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_despacho_anuladas', to=settings.AUTH_USER_MODEL)),
                ('bodega', models.ForeignKey(blank=True, help_text='Bodega de origen. Si no se especifica, se usa la bodega principal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_despacho', to='inventario.bodega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_despacho', to='contactos.cliente')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_despacho_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha_despacho'],
            },
            bases=(apps.core.mixins.AuditDiffMixin, apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('numero', models.CharField(max_length=50)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite de pago.')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento global (0-100).', max_digits=5)),
                ('folio_tributario', models.CharField(blank=True, max_length=50)),
                ('emitido_en', models.DateTimeField(blank=True, null=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_venta_anuladas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_venta', to='contactos.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_venta_emitidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('guia_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_venta', to='ventas.guiadespacho')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
            bases=(apps.core.mixins.AuditDiffMixin, apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GuiaDespachoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('guia_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.guiadespacho')),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.impuesto')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guia_despacho_items', to='productos.producto')),
            ],
            bases=(apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FacturaVentaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento por línea (0-100).', max_digits=5)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Tasa de impuesto desnormalizada al momento de emisión.', max_digits=5)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('factura_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.facturaventa')),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.impuesto')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura_venta_items', to='productos.producto')),
                ('guia_item', models.ForeignKey(blank=True, help_text='Item de guía de despacho origen para trazabilidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_venta_items', to='ventas.guiadespachoitem')),
            ],
            bases=(apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NotaCreditoVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('numero', models.CharField(max_length=50)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('tipo', models.CharField(choices=[('ANULACION', 'Anulación de factura'), ('DESCUENTO', 'Descuento post-factura'), ('DEVOLUCION', 'Devolución de mercadería'), ('CORRECCION', 'Corrección de precio')], default='ANULACION', max_length=20)),
                ('fecha_emision', models.DateField()),
                ('motivo', models.TextField(help_text='Motivo de la emisión de la nota de crédito.')),
                ('folio_tributario', models.CharField(blank=True, max_length=50)),
                ('emitido_en', models.DateTimeField(blank=True, null=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_anuladas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_venta', to='contactos.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_emitidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('factura_origen', models.ForeignKey(help_text='Factura de venta que origina la nota de crédito.', on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='ventas.facturaventa')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
            bases=(apps.core.mixins.AuditDiffMixin, apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NotaCreditoVentaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('factura_item', models.ForeignKey(blank=True, help_text='Item de factura original para trazabilidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_credito_items', to='ventas.facturaventaitem')),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.impuesto')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.notacreditoventa')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nota_credito_venta_items', to='productos.producto')),
            ],
            bases=(apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PedidoVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('numero', models.CharField(max_length=50)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('EN_PROCESO', 'En proceso'), ('DESPACHADO', 'Despachado'), ('FACTURADO', 'Facturado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('fecha_emision', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, help_text='Fecha de entrega comprometida.', null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento global sobre el total (0-100).', max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venta', to='contactos.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('lista_precio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_venta', to='productos.listaprecio')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
            bases=(apps.core.mixins.AuditDiffMixin, apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='guiadespacho',
            name='pedido_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_despacho', to='ventas.pedidoventa'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='pedido_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_venta', to='ventas.pedidoventa'),
        ),
        migrations.CreateModel(
            name='PedidoVentaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento por línea (0-100).', max_digits=5)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Tasa de impuesto desnormalizada al momento del pedido.', max_digits=5)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.impuesto')),
                ('pedido_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.pedidoventa')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_venta_items', to='productos.producto')),
            ],
            bases=(apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='guiadespachoitem',
            name='pedido_item',
            field=models.ForeignKey(blank=True, help_text='Item de pedido de origen para trazabilidad de despacho.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guia_despacho_items', to='ventas.pedidoventaitem'),
        ),
        migrations.CreateModel(
            name='VentaHistorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('PEDIDO', 'Pedido de Venta'), ('GUIA', 'Guía de Despacho'), ('FACTURA', 'Factura de Venta'), ('NOTA_CREDITO', 'Nota de Crédito')], max_length=20)),
                ('documento_id', models.UUIDField(help_text='ID del documento al que pertenece este registro de historial.')),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('motivo', models.TextField(blank=True)),
                ('cambios', models.JSONField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='facturaventaitem',
            index=models.Index(fields=['empresa', 'factura_venta'], name='ventas_fact_empresa_5a2c97_idx'),
        ),
        migrations.AddIndex(
            model_name='notacreditoventa',
            index=models.Index(fields=['empresa', 'numero'], name='ventas_nota_empresa_f21164_idx'),
        ),
        migrations.AddIndex(
            model_name='notacreditoventa',
            index=models.Index(fields=['empresa', 'cliente'], name='ventas_nota_empresa_1b2460_idx'),
        ),
        migrations.AddIndex(
            model_name='notacreditoventa',
            index=models.Index(fields=['empresa', 'estado'], name='ventas_nota_empresa_dff257_idx'),
        ),
        migrations.AddIndex(
            model_name='notacreditoventa',
            index=models.Index(fields=['empresa', 'factura_origen'], name='ventas_nota_empresa_86abb1_idx'),
        ),
        migrations.AddIndex(
            model_name='notacreditoventa',
            index=models.Index(fields=['empresa', 'fecha_emision'], name='ventas_nota_empresa_7432ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='notacreditoventa',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='unique_numero_nota_credito_venta_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='notacreditoventaitem',
            index=models.Index(fields=['empresa', 'nota_credito'], name='ventas_nota_empresa_2e8e41_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoventa',
            index=models.Index(fields=['empresa', 'numero'], name='ventas_pedi_empresa_a49eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoventa',
            index=models.Index(fields=['empresa', 'cliente'], name='ventas_pedi_empresa_849340_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoventa',
            index=models.Index(fields=['empresa', 'estado'], name='ventas_pedi_empresa_4d1373_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoventa',
            index=models.Index(fields=['empresa', 'fecha_emision'], name='ventas_pedi_empresa_1a33ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidoventa',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='unique_numero_pedido_venta_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='guiadespacho',
            index=models.Index(fields=['empresa', 'numero'], name='ventas_guia_empresa_f80d94_idx'),
        ),
        migrations.AddIndex(
            model_name='guiadespacho',
            index=models.Index(fields=['empresa', 'cliente'], name='ventas_guia_empresa_63dc3b_idx'),
        ),
        migrations.AddIndex(
            model_name='guiadespacho',
            index=models.Index(fields=['empresa', 'estado'], name='ventas_guia_empresa_bf631c_idx'),
        ),
        migrations.AddIndex(
            model_name='guiadespacho',
            index=models.Index(fields=['empresa', 'pedido_venta'], name='ventas_guia_empresa_9e60ee_idx'),
        ),
        migrations.AddIndex(
            model_name='guiadespacho',
            index=models.Index(fields=['empresa', 'fecha_despacho'], name='ventas_guia_empresa_b5b1a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='guiadespacho',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='unique_numero_guia_despacho_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['empresa', 'numero'], name='ventas_fact_empresa_a86f53_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['empresa', 'cliente'], name='ventas_fact_empresa_2b76ad_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['empresa', 'estado'], name='ventas_fact_empresa_68978f_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['empresa', 'fecha_emision'], name='ventas_fact_empresa_a61b39_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['empresa', 'fecha_vencimiento'], name='ventas_fact_empresa_2655af_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['empresa', 'pedido_venta'], name='ventas_fact_empresa_6c3447_idx'),
        ),
        migrations.AddConstraint(
            model_name='facturaventa',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='unique_numero_factura_venta_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='pedidoventaitem',
            index=models.Index(fields=['empresa', 'pedido_venta'], name='ventas_pedi_empresa_31bd84_idx'),
        ),
        migrations.AddIndex(
            model_name='guiadespachoitem',
            index=models.Index(fields=['empresa', 'guia_despacho'], name='ventas_guia_empresa_bb04d1_idx'),
        ),
        migrations.AddIndex(
            model_name='guiadespachoitem',
            index=models.Index(fields=['empresa', 'pedido_item'], name='ventas_guia_empresa_b8416a_idx'),
        ),
        migrations.AddIndex(
            model_name='ventahistorial',
            index=models.Index(fields=['empresa', 'tipo_documento', 'documento_id'], name='ventas_vent_empresa_731658_idx'),
        ),
        migrations.AddIndex(
            model_name='ventahistorial',
            index=models.Index(fields=['empresa', 'creado_en'], name='ventas_vent_empresa_c4a171_idx'),
        ),
    ]
