# Generated by Django 6.0.2 on 2026-03-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_facturaventa_enviado_tributario_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='estado_contable',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='guiadespacho',
            name='estado_contable',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='notacreditoventa',
            name='estado_contable',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidoventa',
            name='estado_contable',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=20),
        ),
    ]
