# Generated by Django 6.0.2 on 2026-03-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_facturaventa_estado_contable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='estado_contable',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('REVERSADO', 'Reversado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=20),
        ),
        migrations.AlterField(
            model_name='guiadespacho',
            name='estado_contable',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('REVERSADO', 'Reversado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=20),
        ),
        migrations.AlterField(
            model_name='notacreditoventa',
            name='estado_contable',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('REVERSADO', 'Reversado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='estado_contable',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('REVERSADO', 'Reversado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=20),
        ),
    ]
