# Generated by Django 6.0.2 on 2026-03-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_pedidofactura_presupuesto_origen'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facturaventa',
            new_name='ventas_fact_empresa_652b3b_idx',
            old_name='ventas_fact_empresa_4089e3_idx',
        ),
        migrations.RenameIndex(
            model_name='pedidoventa',
            new_name='ventas_pedi_empresa_1fd955_idx',
            old_name='ventas_pedi_empresa_25e884_idx',
        ),
    ]
