# Generated by Django 6.0.2 on 2026-03-20 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_movimientobancario_estado_contable'),
        ('presupuestos', '0005_alter_presupuestoitem_descripcion'),
        ('productos', '0006_producto_usa_series_listaprecio_listaprecioitem_and_more'),
        ('ventas', '0006_rename_ventas_fact_empresa_4089e3_idx_ventas_fact_empresa_652b3b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventaitem',
            name='presupuesto_item_origen',
            field=models.ForeignKey(blank=True, help_text='Item de presupuesto origen para trazabilidad comercial y control de consumo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_venta_items', to='presupuestos.presupuestoitem'),
        ),
        migrations.AddField(
            model_name='pedidoventaitem',
            name='presupuesto_item_origen',
            field=models.ForeignKey(blank=True, help_text='Item de presupuesto origen para trazabilidad comercial y control de consumo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_venta_items', to='presupuestos.presupuestoitem'),
        ),
        migrations.AddIndex(
            model_name='facturaventaitem',
            index=models.Index(fields=['empresa', 'presupuesto_item_origen'], name='ventas_fact_empresa_20fca8_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoventaitem',
            index=models.Index(fields=['empresa', 'presupuesto_item_origen'], name='ventas_pedi_empresa_daadc7_idx'),
        ),
    ]
