# Generated by Django 6.0.2 on 2026-03-20 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_pedidoventaitem_presupuesto_item_origen_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facturaventaitem',
            new_name='ventas_fact_empresa_38fa85_idx',
            old_name='ventas_fact_empresa_20fca8_idx',
        ),
    ]
