# Generated by Django 6.0.2 on 2026-02-26 16:19

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('CONSTRUCTORA', 'Constructora'), ('VETERINARIA', 'Veterinaria'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro')], default='FREE', max_length=20),
        ),
        migrations.CreateModel(
            name='SecuenciaDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('PRESUPUESTO', 'Presupuesto'), ('FACTURA', 'Factura'), ('GUIA', 'Guía')], max_length=30)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'tipo_documento')},
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
