# Generated by Django 6.0.2 on 2026-02-24 20:13

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_modelprueba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelprueba',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='modelprueba',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
