# Generated by Django 6.0.2 on 2026-03-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permisomodulo_remove_user_empresa_remove_user_rol_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secuenciadocumento',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='secuenciadocumento',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento'), name='secuencia_unica_por_empresa_y_tipo'),
        ),
    ]
