# Generated by Django 6.0.2 on 2026-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='margen_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='politica_precio',
            field=models.CharField(choices=[('fijo', 'Precio fijo'), ('editable', 'Precio editable')], default='fijo', max_length=20),
        ),
    ]
