# Generated by Django 6.0.2 on 2026-02-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_margen_minimo_empresa_politica_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
