# Generated by Django 6.0.2 on 2026-03-06 19:14

import apps.core.storage.public_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plantillapermisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage.public_storage.PublicMediaStorage(), upload_to=''),
        ),
    ]
