# Generated by Django 6.0.2 on 2026-03-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuenciadocumento',
            name='padding',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='secuenciadocumento',
            name='prefijo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
