# Generated by Django 6.0.2 on 2026-03-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_secuenciadocumento_padding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuenciadocumento',
            name='tipo_documento',
            field=models.CharField(choices=[('PRESUPUESTO', 'Presupuesto'), ('FACTURA', 'Factura'), ('GUIA', 'Guía'), ('ORDEN_COMPRA', 'Orden de Compra'), ('DOCUMENTO_COMPRA', 'Documento de Compra')], max_length=30),
        ),
    ]
