# Generated by Django 6.0.2 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_secuenciadocumento_tipo_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secuenciadocumento",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("PRESUPUESTO", "Presupuesto"),
                    ("FACTURA", "Factura"),
                    ("GUIA", "Guía"),
                    ("ORDEN_COMPRA", "Orden de Compra"),
                    ("DOCUMENTO_COMPRA", "Documento de Compra"),
                    ("PEDIDO_VENTA", "Pedido de Venta"),
                    ("FACTURA_VENTA", "Factura de Venta"),
                    ("GUIA_DESPACHO", "Guía de Despacho"),
                    ("NOTA_CREDITO_VENTA", "Nota de Crédito Venta"),
                ],
                max_length=30,
            ),
        ),
    ]
