# Generated by Django 6.0.2 on 2026-03-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_domainevent_outboxevent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='domainevent',
            name='uniq_domain_event_idempotency_per_empresa',
        ),
        migrations.RemoveConstraint(
            model_name='outboxevent',
            name='uniq_outbox_dedup_per_empresa',
        ),
        migrations.AlterField(
            model_name='domainevent',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='dedup_key',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddConstraint(
            model_name='domainevent',
            constraint=models.UniqueConstraint(fields=('empresa', 'idempotency_key'), name='uniq_domain_event_idempotency_per_empresa'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.UniqueConstraint(fields=('empresa', 'dedup_key'), name='uniq_outbox_dedup_per_empresa'),
        ),
    ]
