# Generated by Django 6.0.2 on 2026-03-13 01:41

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_domainevent_uniq_domain_event_idempotency_per_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=80)),
                ('simbolo', models.CharField(blank=True, max_length=10)),
                ('decimales', models.PositiveSmallIntegerField(default=2)),
                ('tasa_referencia', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('es_base', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            options={
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['empresa', 'codigo'], name='core_moneda_empresa_820611_idx'), models.Index(fields=['empresa', 'activa'], name='core_moneda_empresa_71a65f_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_moneda_codigo_por_empresa')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
