# Generated by Django 6.0.2 on 2026-03-19 22:43

import apps.core.mixins
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cuentaporcobrar_cuentaporpagar_tipocambio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancariaEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=120)),
                ('tipo_cuenta', models.CharField(choices=[('CORRIENTE', 'Cuenta corriente'), ('VISTA', 'Cuenta vista'), ('AHORRO', 'Cuenta de ahorro')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=150)),
                ('saldo_referencial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias_empresa', to='core.moneda')),
            ],
            bases=(apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('CREDITO', 'Credito'), ('DEBITO', 'Debito')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORTACION', 'Importacion'), ('CONCILIACION', 'Conciliacion')], default='MANUAL', max_length=20)),
                ('conciliado', models.BooleanField(default=False)),
                ('conciliado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_bancarios', to='core.cuentabancariaempresa')),
                ('cuenta_por_cobrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios', to='core.cuentaporcobrar')),
                ('cuenta_por_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios', to='core.cuentaporpagar')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            bases=(apps.core.mixins.TenantRelationValidationMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RangoFolioTributario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('FACTURA_VENTA', 'Factura de venta'), ('GUIA_DESPACHO', 'Guia de despacho'), ('NOTA_CREDITO_VENTA', 'Nota de credito de venta')], max_length=40)),
                ('caf_nombre', models.CharField(max_length=120)),
                ('folio_desde', models.PositiveIntegerField()),
                ('folio_hasta', models.PositiveIntegerField()),
                ('folio_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_autorizacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionTributaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ambiente', models.CharField(choices=[('CERTIFICACION', 'Certificacion'), ('PRODUCCION', 'Produccion')], default='CERTIFICACION', max_length=20)),
                ('rut_emisor', models.CharField(max_length=12)),
                ('razon_social', models.CharField(max_length=200)),
                ('certificado_alias', models.CharField(blank=True, max_length=150)),
                ('certificado_activo', models.BooleanField(default=False)),
                ('resolucion_numero', models.PositiveIntegerField(blank=True, null=True)),
                ('resolucion_fecha', models.DateField(blank=True, null=True)),
                ('email_intercambio_dte', models.EmailField(blank=True, max_length=254)),
                ('proveedor_envio', models.CharField(blank=True, max_length=80)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'activa'], name='core_config_empresa_16c229_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa',), name='unique_configuracion_tributaria_por_empresa')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='cuentabancariaempresa',
            index=models.Index(fields=['empresa', 'activa'], name='core_cuenta_empresa_f7efb4_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentabancariaempresa',
            index=models.Index(fields=['empresa', 'banco'], name='core_cuenta_empresa_0e7816_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuentabancariaempresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_cuenta'), name='uniq_cuenta_bancaria_empresa_numero'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['empresa', 'fecha'], name='core_movimi_empresa_16a7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['empresa', 'conciliado'], name='core_movimi_empresa_1ecac4_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['empresa', 'cuenta_bancaria', 'fecha'], name='core_movimi_empresa_69a4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='rangofoliotributario',
            index=models.Index(fields=['empresa', 'tipo_documento', 'activo'], name='core_rangof_empresa_8c589a_idx'),
        ),
        migrations.AddIndex(
            model_name='rangofoliotributario',
            index=models.Index(fields=['empresa', 'fecha_vencimiento'], name='core_rangof_empresa_0a198c_idx'),
        ),
    ]
