# Generated by Django 6.0.2 on 2026-03-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cuentabancariaempresa_movimientobancario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuenciadocumento',
            name='tipo_documento',
            field=models.CharField(choices=[('PRESUPUESTO', 'Presupuesto'), ('FACTURA', 'Factura'), ('GUIA', 'Guia'), ('ORDEN_COMPRA', 'Orden de Compra'), ('DOCUMENTO_COMPRA', 'Documento de Compra'), ('PEDIDO_VENTA', 'Pedido de Venta'), ('FACTURA_VENTA', 'Factura de Venta'), ('GUIA_DESPACHO', 'Guia de Despacho'), ('NOTA_CREDITO_VENTA', 'Nota de Credito Venta'), ('ASIENTO_CONTABLE', 'Asiento Contable')], max_length=30),
        ),
    ]
