# Generated by Django 6.0.2 on 2026-03-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_secuenciadocumento_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancario',
            name='estado_contable',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=20),
        ),
    ]
