# Generated by Django 6.0.2 on 2026-03-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_movimientobancario_estado_contable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobancario',
            name='estado_contable',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('REVERSADO', 'Reversado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=20),
        ),
    ]
