# Generated by Django 6.0.2 on 2026-03-13 17:28

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_cuentaporcobrar_cuentaporpagar_tipocambio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('module_code', models.CharField(max_length=60)),
                ('action_code', models.CharField(max_length=80)),
                ('event_type', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('request_id', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('correlation_id', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('event_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'module_code', 'occurred_at'], name='auditoria_a_empresa_7cea06_idx'), models.Index(fields=['empresa', 'event_type', 'occurred_at'], name='auditoria_a_empresa_dbc0de_idx'), models.Index(fields=['empresa', 'entity_type', 'entity_id', 'occurred_at'], name='auditoria_a_empresa_d5d4f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'idempotency_key'), name='uniq_audit_event_idempotency_per_empresa')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
