# Generated by Django 6.0.2 on 2026-03-21 16:51

from django.db import migrations, models


INDEX_RENAMES = (
    ("core_cuentaporcobrar", "tesoreria_c_empresa_a04aea_idx", "core_cuenta_empresa_76c853_idx"),
    ("core_cuentaporcobrar", "tesoreria_c_empresa_3800fc_idx", "core_cuenta_empresa_1bc3b1_idx"),
    ("core_cuentaporpagar", "tesoreria_c_empresa_3bd301_idx", "core_cuenta_empresa_79395e_idx"),
    ("core_cuentaporpagar", "tesoreria_c_empresa_47f820_idx", "core_cuenta_empresa_80bd77_idx"),
    ("core_moneda", "tesoreria_m_empresa_91b345_idx", "core_moneda_empresa_820611_idx"),
    ("core_moneda", "tesoreria_m_empresa_227661_idx", "core_moneda_empresa_71a65f_idx"),
    ("core_tipocambio", "tesoreria_t_empresa_a44b52_idx", "core_tipoca_empresa_3b3185_idx"),
    ("core_tipocambio", "tesoreria_t_empresa_1872c6_idx", "core_tipoca_empresa_c414dc_idx"),
)


def rename_indexes_if_needed(apps, schema_editor):
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        for table_name, old_name, new_name in INDEX_RENAMES:
            constraints = connection.introspection.get_constraints(cursor, table_name)
            if new_name in constraints or old_name not in constraints:
                continue
            schema_editor.execute(
                f"ALTER TABLE `{table_name}` RENAME INDEX `{old_name}` TO `{new_name}`"
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_indexes_if_needed, noop_reverse),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='cuentaporcobrar',
                    new_name='core_cuenta_empresa_76c853_idx',
                    old_name='tesoreria_c_empresa_a04aea_idx',
                ),
                migrations.RenameIndex(
                    model_name='cuentaporcobrar',
                    new_name='core_cuenta_empresa_1bc3b1_idx',
                    old_name='tesoreria_c_empresa_3800fc_idx',
                ),
                migrations.RenameIndex(
                    model_name='cuentaporpagar',
                    new_name='core_cuenta_empresa_79395e_idx',
                    old_name='tesoreria_c_empresa_3bd301_idx',
                ),
                migrations.RenameIndex(
                    model_name='cuentaporpagar',
                    new_name='core_cuenta_empresa_80bd77_idx',
                    old_name='tesoreria_c_empresa_47f820_idx',
                ),
                migrations.RenameIndex(
                    model_name='moneda',
                    new_name='core_moneda_empresa_820611_idx',
                    old_name='tesoreria_m_empresa_91b345_idx',
                ),
                migrations.RenameIndex(
                    model_name='moneda',
                    new_name='core_moneda_empresa_71a65f_idx',
                    old_name='tesoreria_m_empresa_227661_idx',
                ),
                migrations.RenameIndex(
                    model_name='tipocambio',
                    new_name='core_tipoca_empresa_3b3185_idx',
                    old_name='tesoreria_t_empresa_a44b52_idx',
                ),
                migrations.RenameIndex(
                    model_name='tipocambio',
                    new_name='core_tipoca_empresa_c414dc_idx',
                    old_name='tesoreria_t_empresa_1872c6_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='estado_contable',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('REVERSADO', 'Reversado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=20),
        ),
    ]
