# Generated by Django 6.0.2 on 2026-03-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_rename_tesoreria_c_empresa_a04aea_idx_core_cuenta_empresa_76c853_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cuentabancariaempresa',
            new_name='tes_ctabco_emp_act_idx',
            old_name='core_cuenta_empresa_f7efb4_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentabancariaempresa',
            new_name='tes_ctabco_emp_banco_idx',
            old_name='core_cuenta_empresa_0e7816_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentaporcobrar',
            new_name='tes_cxc_emp_cli_est_idx',
            old_name='core_cuenta_empresa_76c853_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentaporcobrar',
            new_name='tes_cxc_emp_ven_idx',
            old_name='core_cuenta_empresa_1bc3b1_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentaporpagar',
            new_name='tes_cxp_emp_prov_est_idx',
            old_name='core_cuenta_empresa_79395e_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentaporpagar',
            new_name='tes_cxp_emp_ven_idx',
            old_name='core_cuenta_empresa_80bd77_idx',
        ),
        migrations.RenameIndex(
            model_name='moneda',
            new_name='tes_moneda_emp_cod_idx',
            old_name='core_moneda_empresa_820611_idx',
        ),
        migrations.RenameIndex(
            model_name='moneda',
            new_name='tes_moneda_emp_act_idx',
            old_name='core_moneda_empresa_71a65f_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientobancario',
            new_name='tes_movbco_emp_fec_idx',
            old_name='core_movimi_empresa_16a7d1_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientobancario',
            new_name='tes_movbco_emp_conc_idx',
            old_name='core_movimi_empresa_1ecac4_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientobancario',
            new_name='tes_movbco_emp_cta_fec_idx',
            old_name='core_movimi_empresa_69a4ae_idx',
        ),
        migrations.RenameIndex(
            model_name='tipocambio',
            new_name='tes_tipocambio_emp_fec_idx',
            old_name='core_tipoca_empresa_3b3185_idx',
        ),
        migrations.RenameIndex(
            model_name='tipocambio',
            new_name='tes_tipocambio_emp_mon_fec_idx',
            old_name='core_tipoca_empresa_c414dc_idx',
        ),
        migrations.AlterModelTable(
            name='cuentabancariaempresa',
            table='tesoreria_cuentabancariaempresa',
        ),
        migrations.AlterModelTable(
            name='cuentaporcobrar',
            table='tesoreria_cuentaporcobrar',
        ),
        migrations.AlterModelTable(
            name='cuentaporpagar',
            table='tesoreria_cuentaporpagar',
        ),
        migrations.AlterModelTable(
            name='moneda',
            table='tesoreria_moneda',
        ),
        migrations.AlterModelTable(
            name='movimientobancario',
            table='tesoreria_movimientobancario',
        ),
        migrations.AlterModelTable(
            name='tipocambio',
            table='tesoreria_tipocambio',
        ),
    ]
