# Generated by Django 6.0.2 on 2026-03-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='configuraciontributaria',
            new_name='fac_cfg_emp_act_idx',
            old_name='core_config_empresa_16c229_idx',
        ),
        migrations.RenameIndex(
            model_name='rangofoliotributario',
            new_name='fac_rango_emp_tipo_act_idx',
            old_name='core_rangof_empresa_8c589a_idx',
        ),
        migrations.RenameIndex(
            model_name='rangofoliotributario',
            new_name='fac_rango_emp_venc_idx',
            old_name='core_rangof_empresa_0a198c_idx',
        ),
        migrations.AlterModelTable(
            name='configuraciontributaria',
            table='facturacion_configuraciontributaria',
        ),
        migrations.AlterModelTable(
            name='rangofoliotributario',
            table='facturacion_rangofoliotributario',
        ),
    ]
