# Generated by Django 6.0.2 on 2026-03-04 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permisomodulo_remove_user_empresa_remove_user_rol_and_more'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='unique_nombre_producto_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'sku'), name='unique_sku_producto_por_empresa'),
        ),
    ]
