# Generated by Django 6.0.2 on 2026-02-25 18:02

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_margen_minimo_empresa_politica_precio'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Compra/Ajuste/Carga Inicial)'), ('salida', 'Salida (Venta/Ajuste/Merma)')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad del movimiento (siempre positiva, el tipo indica dirección)', max_digits=12)),
                ('stock_anterior', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('referencia', models.CharField(help_text='Ej: Factura #50, Ajuste por inventario anual', max_length=150)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-creado_en'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
