# Generated by Django 6.0.2 on 2026-02-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_cliente'),
        ('productos', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='impuesto',
            unique_together={('empresa', 'porcentaje')},
        ),
    ]
