# Generated by Django 6.0.2 on 2026-03-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
    ]
