# Generated by Django 6.0.2 on 2026-03-13 01:41

import django.db.models.deletion
from django.db import migrations, models


def assign_base_currency_to_products(apps, schema_editor):
    Moneda = apps.get_model('core', 'Moneda')
    Producto = apps.get_model('productos', 'Producto')
    moneda_manager = Moneda._base_manager
    producto_manager = Producto._base_manager

    base_by_empresa = {
        moneda.empresa_id: moneda.id
        for moneda in moneda_manager.filter(es_base=True, activa=True)
    }

    for producto in producto_manager.filter(moneda__isnull=True):
        moneda_id = base_by_empresa.get(producto.empresa_id)
        if moneda_id:
            producto.moneda_id = moneda_id
            producto.save(update_fields=['moneda'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_default_monedas'),
        ('productos', '0003_producto_costo_promedio_delete_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.moneda'),
        ),
        migrations.AddField(
            model_name='producto',
            name='permite_decimales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo'), ('GR', 'Gramo'), ('LT', 'Litro'), ('MT', 'Metro'), ('M2', 'Metro Cuadrado'), ('M3', 'Metro Cubico'), ('CJ', 'Caja')], default='UN', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='usa_lotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='usa_vencimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(assign_base_currency_to_products, noop_reverse),
    ]
