# Generated by Django 6.0.2 on 2026-03-13 01:46

from django.db import migrations, models


def normalize_decimal_default(apps, schema_editor):
    Producto = apps.get_model('productos', 'Producto')
    Producto._base_manager.filter(permite_decimales=False).update(permite_decimales=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_moneda_producto_permite_decimales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='permite_decimales',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(normalize_decimal_default, noop_reverse),
    ]
