# Generated by Django 6.0.2 on 2026-03-13 02:14

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_alter_direccion_tipo'),
        ('core', '0015_cuentaporcobrar_cuentaporpagar_tipocambio'),
        ('productos', '0005_alter_producto_permite_decimales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usa_series',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('prioridad', models.PositiveSmallIntegerField(default=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas_precio', to='contactos.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_precio', to='core.moneda')),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.listaprecio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_lista', to='productos.producto')),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='listaprecio',
            index=models.Index(fields=['empresa', 'activa', 'fecha_desde'], name='productos_l_empresa_7a98dc_idx'),
        ),
        migrations.AddIndex(
            model_name='listaprecio',
            index=models.Index(fields=['empresa', 'cliente', 'activa'], name='productos_l_empresa_a634c6_idx'),
        ),
        migrations.AddIndex(
            model_name='listaprecioitem',
            index=models.Index(fields=['empresa', 'producto'], name='productos_l_empresa_3e0c04_idx'),
        ),
        migrations.AddConstraint(
            model_name='listaprecioitem',
            constraint=models.UniqueConstraint(fields=('empresa', 'lista', 'producto'), name='uniq_lista_producto_empresa'),
        ),
    ]
