# Generated by Django 6.0.2 on 2026-03-23 12:00

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_domainevent_outboxevent"),
        ("productos", "0007_move_moneda_relation_to_tesoreria"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("producto_id_ref", models.UUIDField(db_index=True)),
                ("version", models.PositiveIntegerField()),
                ("event_type", models.CharField(max_length=120)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("creado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_creados", to=settings.AUTH_USER_MODEL)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_registros", to="core.empresa")),
                ("producto", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="snapshots_maestro", to="productos.producto")),
            ],
            options={
                "ordering": ["-version", "-creado_en"],
                "indexes": [
                    models.Index(fields=["empresa", "producto_id_ref", "version"], name="productos_p_empresa_79dbf7_idx"),
                    models.Index(fields=["empresa", "event_type", "creado_en"], name="productos_p_empresa_74d76e_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("empresa", "producto_id_ref", "version"), name="uniq_producto_snapshot_version_empresa"),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
