# Generated by Django 6.0.2 on 2026-03-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_productosnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productosnapshot',
            new_name='productos_p_empresa_7f984d_idx',
            old_name='productos_p_empresa_79dbf7_idx',
        ),
        migrations.RenameIndex(
            model_name='productosnapshot',
            new_name='productos_p_empresa_1e55b8_idx',
            old_name='productos_p_empresa_74d76e_idx',
        ),
    ]
