# Generated by Django 6.0.2 on 2026-03-10 15:24

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_secuenciadocumento_padding_and_more'),
        ('productos', '0003_producto_costo_promedio_delete_movimientoinventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_anterior', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('documento_tipo', models.CharField(blank=True, choices=[('COMPRA_RECEPCION', 'Recepción de compra'), ('VENTA_FACTURA', 'Factura de venta'), ('AJUSTE', 'Ajuste manual'), ('TRASLADO', 'Traslado bodega')], max_length=50, null=True)),
                ('documento_id', models.UUIDField(blank=True, null=True)),
                ('referencia', models.CharField(max_length=150)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documento_tipo', models.CharField(max_length=50)),
                ('documento_id', models.UUIDField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='inventario.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='productos.producto')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productos.producto')),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='bodega',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='unique_bodega_empresa'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', 'producto'], name='inventario__empresa_45b978_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', 'producto', 'bodega'], name='inventario__empresa_4c1cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', 'documento_tipo'], name='inventario__empresa_fbec5c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', 'creado_en'], name='inventario__empresa_c7397b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockproducto',
            index=models.Index(fields=['empresa', 'producto'], name='inventario__empresa_9b91c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockproducto',
            constraint=models.UniqueConstraint(fields=('empresa', 'producto', 'bodega'), name='unique_producto_bodega'),
        ),
    ]
