# Generated by Django 6.0.2 on 2026-03-10 16:01

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_secuenciadocumento_padding_and_more'),
        ('inventario', '0002_alter_movimientoinventario_documento_tipo_and_more'),
        ('productos', '0003_producto_costo_promedio_delete_movimientoinventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_promedio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valor_stock', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_inventario', to='inventario.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='inventario.movimientoinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_inventario', to='productos.producto')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['empresa', 'producto', 'bodega', 'creado_en'], name='inventario__empresa_bc670c_idx'), models.Index(fields=['empresa', 'creado_en'], name='inventario__empresa_aaaefe_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
