# Generated by Django 6.0.2 on 2026-03-13 02:14

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cuentaporcobrar_cuentaporpagar_tipocambio'),
        ('inventario', '0004_alter_movimientoinventario_documento_tipo_and_more'),
        ('productos', '0005_alter_producto_permite_decimales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lote_codigo', models.CharField(max_length=80)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StockSerie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('serie_codigo', models.CharField(max_length=120)),
                ('lote_codigo', models.CharField(blank=True, max_length=80)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('SALIDA', 'Salida')], default='DISPONIBLE', max_length=20)),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote_codigo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='series_codigos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', 'lote_codigo'], name='inventario__empresa_588ec4_idx'),
        ),
        migrations.AddField(
            model_name='stocklote',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_lote', to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='stocklote',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocklote',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='stocklote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_lote', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='stockserie',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='stockserie',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockserie',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='stockserie',
            name='movimiento_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_entrada', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='stockserie',
            name='movimiento_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_salida', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='stockserie',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='productos.producto'),
        ),
        migrations.AddIndex(
            model_name='stocklote',
            index=models.Index(fields=['empresa', 'producto', 'bodega'], name='inventario__empresa_8bd3af_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklote',
            index=models.Index(fields=['empresa', 'lote_codigo'], name='inventario__empresa_f5d72e_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklote',
            constraint=models.UniqueConstraint(fields=('empresa', 'producto', 'bodega', 'lote_codigo'), name='uniq_stock_lote_empresa_producto_bodega'),
        ),
        migrations.AddIndex(
            model_name='stockserie',
            index=models.Index(fields=['empresa', 'producto', 'estado'], name='inventario__empresa_badd1c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockserie',
            index=models.Index(fields=['empresa', 'serie_codigo'], name='inventario__empresa_52bdf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockserie',
            constraint=models.UniqueConstraint(fields=('empresa', 'producto', 'serie_codigo'), name='uniq_serie_producto_empresa'),
        ),
    ]
