# Generated by Django 6.0.2 on 2026-03-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_stocklote_stockserie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='documento_tipo',
            field=models.CharField(blank=True, choices=[('COMPRA_RECEPCION', 'Recepcion de compra'), ('GUIA_RECEPCION', 'Guia de recepcion'), ('FACTURA_COMPRA', 'Factura de compra'), ('PEDIDO_VENTA', 'Pedido de venta'), ('VENTA_FACTURA', 'Factura de venta'), ('AJUSTE', 'Ajuste manual'), ('TRASLADO', 'Traslado bodega'), ('PRESUPUESTO', 'Presupuesto')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservastock',
            name='documento_tipo',
            field=models.CharField(choices=[('COMPRA_RECEPCION', 'Recepcion de compra'), ('GUIA_RECEPCION', 'Guia de recepcion'), ('FACTURA_COMPRA', 'Factura de compra'), ('PEDIDO_VENTA', 'Pedido de venta'), ('VENTA_FACTURA', 'Factura de venta'), ('AJUSTE', 'Ajuste manual'), ('TRASLADO', 'Traslado bodega'), ('PRESUPUESTO', 'Presupuesto')], max_length=50),
        ),
    ]
