# Generated by Django 6.0.2 on 2026-03-24 22:21

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_documentos_masivos_inventario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajusteinventariomasivo',
            options={'ordering': ['-creado_en', '-id']},
        ),
        migrations.AlterModelOptions(
            name='ajusteinventariomasivoitem',
            options={'ordering': ['creado_en', 'id']},
        ),
        migrations.AlterModelOptions(
            name='bodega',
            options={'ordering': ['nombre', 'id']},
        ),
        migrations.AlterModelOptions(
            name='trasladoinventariomasivo',
            options={'ordering': ['-creado_en', '-id']},
        ),
        migrations.AlterModelOptions(
            name='trasladoinventariomasivoitem',
            options={'ordering': ['creado_en', 'id']},
        ),
        migrations.AlterModelManagers(
            name='ajusteinventariomasivo',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ajusteinventariomasivoitem',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='trasladoinventariomasivo',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='trasladoinventariomasivoitem',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='ajusteinventariomasivo',
            new_name='inventario__empresa_b695cc_idx',
            old_name='inventario_a_empresa_85ff68_idx',
        ),
        migrations.RenameIndex(
            model_name='ajusteinventariomasivo',
            new_name='inventario__empresa_2e5cae_idx',
            old_name='inventario_a_empresa_74ba9f_idx',
        ),
        migrations.RenameIndex(
            model_name='ajusteinventariomasivo',
            new_name='inventario__empresa_805f99_idx',
            old_name='inventario_a_empresa_529416_idx',
        ),
        migrations.RenameIndex(
            model_name='ajusteinventariomasivoitem',
            new_name='inventario__empresa_46c8d9_idx',
            old_name='inventario_a_empresa_4feea4_idx',
        ),
        migrations.RenameIndex(
            model_name='ajusteinventariomasivoitem',
            new_name='inventario__empresa_7bb092_idx',
            old_name='inventario_a_empresa_645804_idx',
        ),
        migrations.RenameIndex(
            model_name='trasladoinventariomasivo',
            new_name='inventario__empresa_26b3d5_idx',
            old_name='inventario_t_empresa_1aa8f0_idx',
        ),
        migrations.RenameIndex(
            model_name='trasladoinventariomasivo',
            new_name='inventario__empresa_0e4769_idx',
            old_name='inventario_t_empresa_57a715_idx',
        ),
        migrations.RenameIndex(
            model_name='trasladoinventariomasivo',
            new_name='inventario__empresa_89612b_idx',
            old_name='inventario_t_empresa_35c62b_idx',
        ),
        migrations.RenameIndex(
            model_name='trasladoinventariomasivoitem',
            new_name='inventario__empresa_668163_idx',
            old_name='inventario_t_empresa_476503_idx',
        ),
        migrations.RenameIndex(
            model_name='trasladoinventariomasivoitem',
            new_name='inventario__empresa_449e10_idx',
            old_name='inventario_t_empresa_e6b16f_idx',
        ),
    ]
