# Generated by Django 6.0.2 on 2026-03-27 18:06

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_move_facturacion_models_to_facturacion_app'),
        ('inventario', '0010_ajusteinventariomasivoitem_lote_y_vencimiento'),
        ('productos', '0009_rename_productos_p_empresa_79dbf7_idx_productos_p_empresa_7f984d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('numero', models.CharField(max_length=50)),
                ('fecha_corte', models.DateField()),
                ('reservado_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('disponible_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha_corte', '-creado_en', '-id'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CorteInventarioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto_nombre', models.CharField(max_length=255)),
                ('producto_sku', models.CharField(blank=True, default='', max_length=120)),
                ('producto_categoria_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('bodega_nombre', models.CharField(max_length=120)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reservado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('valor_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lotes_activos', models.CharField(blank=True, default='', max_length=500)),
                ('proximo_vencimiento', models.DateField(blank=True, null=True)),
                ('series_disponibles', models.PositiveIntegerField(default=0)),
                ('series_muestra', models.CharField(blank=True, default='', max_length=255)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_inventario', to='inventario.bodega')),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.corteinventario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_inventario', to='productos.producto')),
            ],
            options={
                'ordering': ['producto_nombre', 'bodega_nombre', 'id'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='corteinventario',
            index=models.Index(fields=['empresa', 'fecha_corte'], name='inventario__empresa_6f197a_idx'),
        ),
        migrations.AddIndex(
            model_name='corteinventario',
            index=models.Index(fields=['empresa', 'estado'], name='inventario__empresa_45630b_idx'),
        ),
        migrations.AddIndex(
            model_name='corteinventario',
            index=models.Index(fields=['empresa', 'numero'], name='inventario__empresa_68a36c_idx'),
        ),
        migrations.AddIndex(
            model_name='corteinventarioitem',
            index=models.Index(fields=['empresa', 'corte'], name='inventario__empresa_4043fe_idx'),
        ),
        migrations.AddIndex(
            model_name='corteinventarioitem',
            index=models.Index(fields=['empresa', 'producto'], name='inventario__empresa_e17822_idx'),
        ),
        migrations.AddIndex(
            model_name='corteinventarioitem',
            index=models.Index(fields=['empresa', 'bodega'], name='inventario__empresa_bedd4b_idx'),
        ),
    ]
