# Generated by Django 6.0.2 on 2026-03-27 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_move_facturacion_models_to_facturacion_app'),
        ('inventario', '0011_corteinventario_corteinventarioitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corteinventario',
            name='periodo_referencia',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='corteinventario',
            name='tipo_corte',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('CIERRE_MENSUAL', 'Cierre mensual')], default='MANUAL', max_length=30),
        ),
        migrations.AddIndex(
            model_name='corteinventario',
            index=models.Index(fields=['empresa', 'tipo_corte', 'periodo_referencia'], name='inventario__empresa_2fcf05_idx'),
        ),
        migrations.AddConstraint(
            model_name='corteinventario',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_corte', 'CIERRE_MENSUAL')), fields=('empresa', 'tipo_corte', 'periodo_referencia'), name='inventario_cierre_mensual_unico_por_periodo'),
        ),
    ]
