# Generated by Django 6.0.2 on 2026-03-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_corteinventario_periodo_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='corteinventario',
            name='inventario_cierre_mensual_unico_por_periodo',
        ),
    ]
