# Generated by Django 6.0.2 on 2026-02-26 13:47

import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_credito', models.PositiveIntegerField(default=0)),
                ('categoria_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('segmento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['contacto__nombre'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('rut', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('tipo', models.CharField(choices=[('PERSONA', 'Persona Natural'), ('EMPRESA', 'Empresa')], default='PERSONA', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('CORRIENTE', 'Cuenta Corriente'), ('VISTA', 'Cuenta Vista'), ('AHORRO', 'Cuenta de Ahorro')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=255)),
                ('rut_titular', models.CharField(max_length=12)),
                ('activa', models.BooleanField(default=True)),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('FACTURACION', 'Facturación'), ('DESPACHO', 'Despacho'), ('COMERCIAL', 'Comercial')], max_length=20)),
                ('direccion', models.TextField()),
                ('comuna', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='CHILE', max_length=100)),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('giro', models.CharField(blank=True, max_length=255, null=True)),
                ('vendedor_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('dias_credito', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['contacto__nombre'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
