# Generated by Django 6.0.2 on 2026-02-25 20:02

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_delete_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('rut', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('tipo', models.CharField(choices=[('persona', 'Persona'), ('empresa', 'Empresa')], default='persona', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
            ],
            options={
                'ordering': ['nombre'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_credito', models.PositiveIntegerField(default=0)),
                ('categoria_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('segmento', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='contactos.contacto')),
            ],
            options={
                'ordering': ['contacto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Cuenta Corriente'), ('vista', 'Cuenta Vista'), ('ahorro', 'Cuenta de Ahorro')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=255)),
                ('rut_titular', models.CharField(max_length=12)),
                ('activa', models.BooleanField(default=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='contactos.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('facturacion', 'Facturación'), ('despacho', 'Despacho'), ('comercial', 'Comercial')], max_length=20)),
                ('direccion', models.TextField()),
                ('comuna', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='Chile', max_length=100)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='contactos.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giro', models.CharField(blank=True, max_length=255, null=True)),
                ('vendedor_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('dias_credito', models.PositiveIntegerField(default=0)),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='contactos.contacto')),
            ],
            options={
                'ordering': ['contacto__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['empresa', 'nombre'], name='contactos_c_empresa_b7ae2d_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['empresa', 'activo'], name='contactos_c_empresa_0862e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.UniqueConstraint(fields=('empresa', 'rut'), name='unique_contacto_rut_empresa'),
        ),
        migrations.AddIndex(
            model_name='cuentabancaria',
            index=models.Index(fields=['contacto', 'activa'], name='contactos_c_contact_7d5712_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuentabancaria',
            constraint=models.UniqueConstraint(fields=('contacto', 'numero_cuenta'), name='unique_cuenta_por_contacto'),
        ),
        migrations.AddIndex(
            model_name='direccion',
            index=models.Index(fields=['contacto', 'tipo'], name='contactos_d_contact_3921bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='direccion',
            constraint=models.UniqueConstraint(fields=('contacto', 'tipo'), name='unique_tipo_direccion_por_contacto'),
        ),
    ]
