# Generated by Django 6.0.2 on 2026-02-26 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='contactos.contacto'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='contactos.contacto'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='contactos.contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='contactos.contacto'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['empresa', 'nombre'], name='contactos_c_empresa_b7ae2d_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['empresa', 'activo'], name='contactos_c_empresa_0862e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.UniqueConstraint(fields=('empresa', 'rut'), name='unique_contacto_rut_empresa'),
        ),
        migrations.AddIndex(
            model_name='cuentabancaria',
            index=models.Index(fields=['contacto', 'activa'], name='contactos_c_contact_7d5712_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuentabancaria',
            constraint=models.UniqueConstraint(fields=('contacto', 'numero_cuenta'), name='unique_cuenta_por_contacto'),
        ),
        migrations.AddIndex(
            model_name='direccion',
            index=models.Index(fields=['contacto', 'tipo'], name='contactos_d_contact_3921bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='direccion',
            constraint=models.UniqueConstraint(fields=('contacto', 'tipo'), name='unique_tipo_direccion_por_contacto'),
        ),
    ]
