# Generated by Django 6.0.2 on 2026-02-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='tipo',
            field=models.CharField(choices=[('FACTURACION', 'Facturación'), ('DESPACHO', 'Despacho'), ('COMERCIAL', 'Comercial'), ('PERSONAL', 'Personal')], max_length=20),
        ),
    ]
