# Generated by Codex on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactos", "0004_alter_contacto_email_alter_contacto_rut"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contacto",
            constraint=models.CheckConstraint(
                condition=~models.Q(rut=""),
                name="check_contacto_rut_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="contacto",
            constraint=models.CheckConstraint(
                condition=~models.Q(email=""),
                name="check_contacto_email_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="contacto",
            constraint=models.CheckConstraint(
                condition=~models.Q(tipo=""),
                name="check_contacto_tipo_not_empty",
            ),
        ),
    ]
