# Generated by Django 6.0.2 on 2026-02-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_presupuestoitem_impuesto_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestohistorial',
            name='cambios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
