# Generated by Django 6.0.2 on 2026-03-05 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_alter_direccion_tipo'),
        ('core', '0005_empresa_logo'),
        ('presupuestos', '0003_presupuestohistorial_cambios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='presupuesto',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='unique_numero_per_empresa'),
        ),
    ]
