# Generated by Django 6.0.2 on 2026-03-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_presupuesto_unique_numero_per_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoitem',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
