# Generated by Django 6.0.2 on 2026-03-10 18:54

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_recepcion_sin_oc'),
        ('contactos', '0003_alter_direccion_tipo'),
        ('core', '0008_secuenciadocumento_padding_and_more'),
        ('productos', '0003_producto_costo_promedio_delete_movimientoinventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCompraProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('GUIA_RECEPCION', 'Guía de recepción'), ('FACTURA_COMPRA', 'Factura de compra')], max_length=20)),
                ('folio', models.CharField(max_length=50)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('fecha_emision', models.DateField()),
                ('fecha_recepcion', models.DateField()),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('uuid_externo', models.UUIDField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_compra', to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_compra', to='contactos.proveedor')),
                ('recepcion_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_compra', to='compras.recepcioncompra')),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCompraProveedorItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.documentocompraproveedor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_registros', to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('recepcion_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_items', to='compras.recepcioncompraitem')),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='documentocompraproveedor',
            index=models.Index(fields=['empresa', 'proveedor'], name='compras_doc_empresa_3cfb89_idx'),
        ),
        migrations.AddIndex(
            model_name='documentocompraproveedor',
            index=models.Index(fields=['empresa', 'tipo_documento', 'estado'], name='compras_doc_empresa_ce17c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentocompraproveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('uuid_externo__isnull', False)), fields=('empresa', 'uuid_externo'), name='unique_uuid_externo_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='documentocompraproveedoritem',
            index=models.Index(fields=['empresa', 'documento'], name='compras_doc_empresa_69e721_idx'),
        ),
    ]
