# Generated by Django 6.0.2 on 2026-03-10 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_documento_compra_proveedor'),
        ('contactos', '0003_alter_direccion_tipo'),
        ('core', '0008_secuenciadocumento_padding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocompraproveedor',
            name='corregido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentocompraproveedor',
            name='corregido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_compra_corregidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentocompraproveedor',
            name='documento_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_correccion', to='compras.documentocompraproveedor'),
        ),
        migrations.AddField(
            model_name='documentocompraproveedor',
            name='motivo_correccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='documentocompraproveedor',
            index=models.Index(fields=['empresa', 'documento_origen'], name='compras_doc_empresa_6df00e_idx'),
        ),
    ]
