# Generated by Django 6.0.2 on 2026-03-13 00:12

from django.conf import settings
from django.db import migrations, models


def backfill_bloquea_duplicado(apps, schema_editor):
    DocumentoCompraProveedor = apps.get_model('compras', 'DocumentoCompraProveedor')
    DocumentoCompraProveedor._base_manager.filter(estado='ANULADO').update(bloquea_duplicado=False)


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_documentocompraproveedor_unique_proveedor_tipo_folio_serie'),
        ('contactos', '0003_alter_direccion_tipo'),
        ('core', '0012_remove_domainevent_uniq_domain_event_idempotency_per_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentocompraproveedor',
            name='uniq_doc_compra_emp_prov_tipo_folio_serie',
        ),
        migrations.AddField(
            model_name='documentocompraproveedor',
            name='bloquea_duplicado',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.RunPython(backfill_bloquea_duplicado, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='documentocompraproveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'proveedor', 'tipo_documento', 'folio', 'serie', 'bloquea_duplicado'), name='uniq_doc_compra_emp_prov_tipo_folio_serie_activo'),
        ),
    ]
