# Generated by Django 6.0.2 on 2026-03-13 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_remove_documentocompraproveedor_uniq_doc_compra_emp_prov_tipo_folio_serie_and_more'),
        ('contactos', '0003_alter_direccion_tipo'),
        ('core', '0012_remove_domainevent_uniq_domain_event_idempotency_per_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentocompraproveedor',
            name='unique_uuid_externo_por_empresa',
        ),
        migrations.AddConstraint(
            model_name='documentocompraproveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'uuid_externo'), name='unique_uuid_externo_por_empresa'),
        ),
    ]
