# Generated by Django 6.0.2 on 2026-03-13 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_remove_documentocompraproveedor_unique_uuid_externo_por_empresa_and_more'),
        ('contactos', '0003_alter_direccion_tipo'),
        ('core', '0014_seed_default_monedas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocompraproveedor',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_compra', to='core.moneda'),
        ),
        migrations.AddIndex(
            model_name='documentocompraproveedor',
            index=models.Index(fields=['empresa', 'moneda'], name='compras_doc_empresa_d62a1c_idx'),
        ),
    ]
