# Generated by Django 6.0.2 on 2026-03-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_audit_documento_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompraitem',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
