# Generated by Django 6.0.2 on 2026-03-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_alter_documentocompraproveedor_tipo_documento_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='enviado_tributario_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='estado_tributario',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_COLA', 'En cola'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='mensaje_tributario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='track_id_tributario',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
